/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.github.gabrielsizilio.sabordecasa.produto;

import java.awt.Component;
import java.awt.SystemColor;
import java.beans.PropertyVetoException;
import java.math.BigDecimal;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Gabriel Sizilio <Gabriel at IFNMG>
 */
public class CadastroProduto extends javax.swing.JInternalFrame {
    
    private static CadastroProduto instance;
    private static final DefaultComboBoxModel<Recheio> boxModel = new DefaultComboBoxModel<>();
    private static final DefaultComboBoxModel<Produto> boxModelProdutos = new DefaultComboBoxModel<>();
    private static Produto produto;
    
    //<editor-fold defaultstate="collapsed" desc="Constructor">
    
    /**
     * Creates new form RegistroProdutos
     */
    public CadastroProduto() {
        initComponents();
        produto = new Produto();

        recheioReload();
        cboRecheio.setModel(boxModel);
        cboRecheio.setRenderer(new RecheioRender());
        
        produtoReload();
        lstProduto.setModel(boxModelProdutos);
        lstProduto.setCellRenderer(new ProdutoRender());
        
        try {
            cboRecheio.setSelectedIndex(0);
        } catch (Exception ex) {
            System.out.println(">> " + ex.getMessage());
        }
    }
//</editor-fold>
    
    public static CadastroProduto getInstance() {
        if(instance == null) {
            instance = new CadastroProduto();
        }
        
        recheioReload();
        return instance;
    }
    
    public static void recheioReload() {
        try {
            int selectedIdx = boxModel.getIndexOf(boxModel.getSelectedItem());
            boxModel.removeAllElements();
            
            boxModel.addAll(new RecheioDao().findAll());
            boxModel.setSelectedItem(boxModel.getElementAt(selectedIdx));
        } catch (Exception ex) {
            System.out.println(">> " + ex.getMessage());
        }
    }
    public static void produtoReload() {
        try {
            int selectedIdx = boxModelProdutos.getIndexOf(boxModelProdutos.getSelectedItem());
            boxModelProdutos.removeAllElements();
            
            boxModelProdutos.addAll(new ProdutoDao().findAll());
            boxModelProdutos.setSelectedItem(boxModelProdutos.getElementAt(selectedIdx));
        } catch (Exception ex) {
            System.out.println(">> " + ex.getMessage());
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskPrincipal = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        btnCriar = new javax.swing.JButton();
        cboRecheio = new javax.swing.JComboBox<>();
        lblRecheio = new javax.swing.JLabel();
        ftfPreco = new javax.swing.JFormattedTextField();
        ckbRecheio = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        bntCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstProduto = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        txtNome1 = new javax.swing.JTextField();
        ftfPreco1 = new javax.swing.JFormattedTextField();
        lblPreco1 = new javax.swing.JLabel();
        lblNome1 = new javax.swing.JLabel();
        lblRecheio1 = new javax.swing.JLabel();
        ckbRecheio1 = new javax.swing.JCheckBox();
        cboRecheio1 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Produto");

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Nome:");
        lblNome.setToolTipText("");

        lblPreco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPreco.setText("Preco base:");
        lblPreco.setToolTipText("");

        btnCriar.setText("Criar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        cboRecheio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboRecheio.setEnabled(false);
        cboRecheio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRecheioActionPerformed(evt);
            }
        });

        lblRecheio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRecheio.setText("Recheio:");
        lblRecheio.setToolTipText("");

        ftfPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        ftfPreco.setText("0,00");
        ftfPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfPrecoActionPerformed(evt);
            }
        });

        ckbRecheio.setToolTipText("");
        ckbRecheio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbRecheioActionPerformed(evt);
            }
        });

        bntCancelar.setText("Cancelar");
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstProduto);

        jLabel1.setText("CRIAR");

        jLabel2.setText("EDITAR");

        btnAtualizar.setText("Atualizar");
        btnAtualizar.setToolTipText("");
        btnAtualizar.setEnabled(false);
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        txtNome1.setEnabled(false);

        ftfPreco1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        ftfPreco1.setText("0,00");
        ftfPreco1.setEnabled(false);
        ftfPreco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfPreco1ActionPerformed(evt);
            }
        });

        lblPreco1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPreco1.setText("Preco base:");
        lblPreco1.setToolTipText("");

        lblNome1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome1.setText("Nome:");
        lblNome1.setToolTipText("");

        lblRecheio1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRecheio1.setText("Recheio:");
        lblRecheio1.setToolTipText("");

        ckbRecheio1.setToolTipText("");
        ckbRecheio1.setEnabled(false);
        ckbRecheio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbRecheio1ActionPerformed(evt);
            }
        });

        cboRecheio1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboRecheio1.setEnabled(false);
        cboRecheio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRecheio1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dskPrincipalLayout = new javax.swing.GroupLayout(dskPrincipal);
        dskPrincipal.setLayout(dskPrincipalLayout);
        dskPrincipalLayout.setHorizontalGroup(
            dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dskPrincipalLayout.createSequentialGroup()
                .addGroup(dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dskPrincipalLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(dskPrincipalLayout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(dskPrincipalLayout.createSequentialGroup()
                                        .addComponent(lblPreco)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ftfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(75, 75, 75))
                    .addGroup(dskPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dskPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dskPrincipalLayout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(dskPrincipalLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bntCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(dskPrincipalLayout.createSequentialGroup()
                                    .addComponent(lblPreco1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ftfPreco1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(dskPrincipalLayout.createSequentialGroup()
                                    .addComponent(lblNome1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(dskPrincipalLayout.createSequentialGroup()
                                    .addComponent(lblRecheio1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ckbRecheio1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cboRecheio1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 51, Short.MAX_VALUE))))
            .addGroup(dskPrincipalLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblRecheio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckbRecheio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboRecheio, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dskPrincipalLayout.setVerticalGroup(
            dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dskPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRecheio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dskPrincipalLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(ckbRecheio))
                    .addGroup(dskPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboRecheio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dskPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dskPrincipalLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPreco1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftfPreco1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRecheio1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dskPrincipalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cboRecheio1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dskPrincipalLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(ckbRecheio1)))
                        .addGap(30, 30, 30)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(bntCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dskPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dskPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        // TODO add your handling code here:
        try {
           
            Recheio recheio = new Recheio();
            
            if(ckbRecheio.isSelected()){
                recheio = (Recheio)boxModel.getSelectedItem();
            } else {
                recheio = null;
            }
            
            new ProdutoDao().saveOrUpdate(new Produto(null, txtNome.getText(), new BigDecimal(ftfPreco.getValue().toString()), recheio));
           
        } catch (Exception e) {
             Logger.getLogger(CadastroRecheio.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, "Record not saved.\nCheck the data or the network connection and try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        Venda.produtoReload();
        produtoReload();
    }//GEN-LAST:event_btnCriarActionPerformed

    private void cboRecheioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRecheioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboRecheioActionPerformed

    private void ftfPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfPrecoActionPerformed

    private void ckbRecheioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbRecheioActionPerformed
        // TODO add your handling code here:
        if(ckbRecheio.isSelected()){
            cboRecheio.setEnabled(true);
        } else {
            cboRecheio.setEnabled(false);
        }
        
    }//GEN-LAST:event_ckbRecheioActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        // TODO add your handling code here:
        //        CANCELAR CRIAÇÃO DE PRODUTO
        dispose();
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:

        try {
            produto.setId(lstProduto.getSelectedValue().getId());
            produto.setNome(txtNome1.getText());
            produto.setPrecoBase(new BigDecimal(ftfPreco1.getValue().toString()));
            produto.setRecheio((Recheio)cboRecheio1.getSelectedItem());
            produto.setValorProduto(lstProduto.getSelectedValue().calcularValorProduto());
            System.out.println(">>>"+produto);
        } catch (Exception ex) {
            Logger.getLogger(EditaProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        new ProdutoDao().saveOrUpdate(produto);
        
        produtoReload();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void ftfPreco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfPreco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfPreco1ActionPerformed

    private void ckbRecheio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbRecheio1ActionPerformed
        // TODO add your handling code here:
        if(ckbRecheio1.isSelected()){
            cboRecheio1.setEnabled(true);
        } else {
            cboRecheio1.setEnabled(false);
        }
    }//GEN-LAST:event_ckbRecheio1ActionPerformed

    private void cboRecheio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRecheio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboRecheio1ActionPerformed
    
    private void attachInternalFrame(JInternalFrame window) {
        // Attach internal window to desktop pane
        if (!window.isVisible()) {
            window.setVisible(true);
            dskPrincipal.add(window);
        }

        // Focus and restore the internal window
        try {
            window.setSelected(true);
            window.setIcon(false);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(CadastroProduto.class.getName())
                    .log(Level.INFO, null, ex);
        }
    }
    
    
    private void clear() {
        txtNome.setText(null);
        txtNome.requestFocus();
        ftfPreco.setValue(null);
    }
    
    private void reloadCampoAtualiar() {
        btnAtualizar.setEnabled(true);
        txtNome1.setEnabled(true);
        txtNome1.setText(lstProduto.getSelectedValue().getNome());

        ftfPreco1.setEnabled(true);
        ftfPreco1.setValue(lstProduto.getSelectedValue().getPrecoBase());

        recheioReload();
        ckbRecheio1.setEnabled(true);
        
        cboRecheio1.setModel(boxModel);
        cboRecheio1.setRenderer(new RecheioRender());
        cboRecheio1.setSelectedItem(lstProduto.getSelectedValue().getRecheio());
    }
    
    private class RecheioRender extends JLabel implements ListCellRenderer<Recheio> {
        @Override
        public Component getListCellRendererComponent(
                JList<? extends Recheio> list, Recheio value, 
                int index, boolean isSelected, boolean cellHasFocus) {
            if(value == null) {
                return this;
            }
            
            setOpaque(true);
            setForeground(SystemColor.textText);
            setBackground(SystemColor.text);
            if(isSelected) {
                setForeground(SystemColor.textHighlightText);
                setBackground(SystemColor.textHighlight);
            }
            
            setText(value.getNome());
            setBorder(BorderFactory.createEmptyBorder(0, 5, 1, 1));
            return this;
        }
    }
    private class ProdutoRender extends JLabel implements ListCellRenderer<Produto> {
        @Override
        public Component getListCellRendererComponent(
                JList<? extends Produto> list, Produto value, 
                int index, boolean isSelected, boolean cellHasFocus) {
            if(value == null) {
                return this;
            }
            
            setOpaque(true);
            setForeground(SystemColor.textText);
            setBackground(SystemColor.text);
            if(isSelected) {
                reloadCampoAtualiar();
                setForeground(SystemColor.textHighlightText);
                setBackground(SystemColor.textHighlight);
            }
            
            setText(value.getNome() 
                    +"      (" + value.getValorProduto() + ")");
            setBorder(BorderFactory.createEmptyBorder(0, 5, 1, 1));
            return this;
        }
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCriar;
    private javax.swing.JComboBox<Recheio> cboRecheio;
    private javax.swing.JComboBox<Recheio> cboRecheio1;
    private javax.swing.JCheckBox ckbRecheio;
    private javax.swing.JCheckBox ckbRecheio1;
    private javax.swing.JPanel dskPrincipal;
    private javax.swing.JFormattedTextField ftfPreco;
    private javax.swing.JFormattedTextField ftfPreco1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblPreco1;
    private javax.swing.JLabel lblRecheio;
    private javax.swing.JLabel lblRecheio1;
    private javax.swing.JList<Produto> lstProduto;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNome1;
    // End of variables declaration//GEN-END:variables
}
