/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.github.yodemisj.sabordecasa.GUI;

import io.github.rianal25.sabordecasa.cliente.Cliente;
import io.github.rianal25.sabordecasa.cliente.Endereco;
import io.github.rianal25.sabordecasa.cliente.Telefone;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rian Alves <Rian at IFNMG>
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblnome = new javax.swing.JLabel();
        lbltelefone = new javax.swing.JLabel();
        lblddd1 = new javax.swing.JLabel();
        lblnumero1 = new javax.swing.JLabel();
        lbltelefone2 = new javax.swing.JLabel();
        lblddd2 = new javax.swing.JLabel();
        lblnumero2 = new javax.swing.JLabel();
        lblendereco = new javax.swing.JLabel();
        lblendereco2 = new javax.swing.JLabel();
        lblopcional1 = new javax.swing.JLabel();
        lblopcional2 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txtddd1 = new javax.swing.JTextField();
        txttelefone1 = new javax.swing.JTextField();
        txtddd2 = new javax.swing.JTextField();
        txttelefone2 = new javax.swing.JTextField();
        btnsalvar = new javax.swing.JButton();
        ckbmensageiro1 = new javax.swing.JCheckBox();
        ckbmensageiro2 = new javax.swing.JCheckBox();
        lblendereco1 = new javax.swing.JLabel();
        lblendereco3 = new javax.swing.JLabel();
        lblendereco4 = new javax.swing.JLabel();
        lblendereco5 = new javax.swing.JLabel();
        lblendereco6 = new javax.swing.JLabel();
        lblendereco7 = new javax.swing.JLabel();
        lblendereco8 = new javax.swing.JLabel();
        lblendereco9 = new javax.swing.JLabel();
        txtendereco1 = new javax.swing.JTextField();
        txtnumero1 = new javax.swing.JTextField();
        txtbairro1 = new javax.swing.JTextField();
        txtcomplemento1 = new javax.swing.JTextField();
        txtendereco2 = new javax.swing.JTextField();
        txtnumero2 = new javax.swing.JTextField();
        txtbairro2 = new javax.swing.JTextField();
        txtendereco8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblnome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblnome.setText("Nome:");

        lbltelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbltelefone.setText("Fone1:");

        lblddd1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblddd1.setText("DDD:");

        lblnumero1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblnumero1.setText("Telefone:");

        lbltelefone2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbltelefone2.setText("Fone2:");

        lblddd2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblddd2.setText("DDD:");

        lblnumero2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblnumero2.setText("Telefone:");

        lblendereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblendereco.setText("Localização1:");

        lblendereco2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblendereco2.setText("Localização2:");

        lblopcional1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblopcional1.setText("Opcional");

        lblopcional2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblopcional2.setText("Opcional");

        txtnome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });

        txtddd1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtddd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtddd1ActionPerformed(evt);
            }
        });

        txttelefone1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txttelefone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefone1ActionPerformed(evt);
            }
        });

        txtddd2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtddd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtddd2ActionPerformed(evt);
            }
        });

        txttelefone2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txttelefone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefone2ActionPerformed(evt);
            }
        });

        btnsalvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnsalvar.setText("Salvar");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        ckbmensageiro1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckbmensageiro1.setText("Mensageiro");

        ckbmensageiro2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckbmensageiro2.setText("Mensageiro");

        lblendereco1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblendereco1.setText("Número:");

        lblendereco3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblendereco3.setText("Endereço:");

        lblendereco4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblendereco4.setText("Bairro:");

        lblendereco5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblendereco5.setText("Complemento:");

        lblendereco6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblendereco6.setText("Endereço:");

        lblendereco7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblendereco7.setText("Bairro:");

        lblendereco8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblendereco8.setText("Complemento:");

        lblendereco9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblendereco9.setText("Número:");

        txtendereco1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtnumero1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtbairro1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtcomplemento1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtendereco2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtnumero2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtbairro2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtendereco8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbltelefone2)
                                .addGap(32, 32, 32)
                                .addComponent(lblopcional1))
                            .addComponent(lbltelefone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(lblddd2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtddd2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblnumero2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txttelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblnome)
                                                .addGap(26, 26, 26)
                                                .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblddd1)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtddd1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(lblnumero1)
                                                .addGap(18, 18, 18)
                                                .addComponent(txttelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ckbmensageiro1)
                                    .addComponent(ckbmensageiro2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblendereco6)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtendereco2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(48, 48, 48)
                                            .addComponent(lblendereco9)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtnumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblendereco7)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtbairro2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(55, 55, 55)
                                            .addComponent(lblendereco8)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtendereco8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblendereco3)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtendereco1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(48, 48, 48)
                                            .addComponent(lblendereco1)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtnumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblendereco4)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtbairro1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(55, 55, 55)
                                            .addComponent(lblendereco5)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtcomplemento1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(lblendereco, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblendereco2)
                                .addGap(35, 35, 35)
                                .addComponent(lblopcional2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addComponent(btnsalvar)))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnome)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(lbltelefone)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtddd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbmensageiro1)
                    .addComponent(lblddd1)
                    .addComponent(lblnumero1))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltelefone2)
                    .addComponent(lblopcional1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblddd2)
                    .addComponent(txtddd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnumero2)
                    .addComponent(ckbmensageiro2)
                    .addComponent(txttelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(lblendereco)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblendereco3)
                    .addComponent(txtendereco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblendereco1))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcomplemento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbairro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblendereco4)
                    .addComponent(lblendereco5))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblendereco2)
                    .addComponent(lblopcional2))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblendereco6)
                    .addComponent(txtendereco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblendereco9))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtendereco8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbairro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblendereco7)
                    .addComponent(lblendereco8))
                .addGap(36, 36, 36)
                .addComponent(btnsalvar)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttelefone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefone1ActionPerformed

    private void txttelefone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefone2ActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // TODO add your handling code here:
        Cliente cliente = new Cliente();
        Telefone telefone = new Telefone();
        Endereco endereco = new Endereco();
        try {
            cliente.setNome(txtnome.getText());
            endereco.setRua(txtendereco1.getText());
            endereco.setNumero((short)80);
            endereco.setBairro(txtbairro1.getText());
            endereco.setComplemento(txtcomplemento1.getText());
            cliente.addEndereco(endereco);
        } catch (Exception ex) {
            Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(">>" + cliente);
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void txtddd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtddd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtddd1ActionPerformed

    private void txtddd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtddd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtddd2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsalvar;
    private javax.swing.JCheckBox ckbmensageiro1;
    private javax.swing.JCheckBox ckbmensageiro2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblddd1;
    private javax.swing.JLabel lblddd2;
    private javax.swing.JLabel lblendereco;
    private javax.swing.JLabel lblendereco1;
    private javax.swing.JLabel lblendereco2;
    private javax.swing.JLabel lblendereco3;
    private javax.swing.JLabel lblendereco4;
    private javax.swing.JLabel lblendereco5;
    private javax.swing.JLabel lblendereco6;
    private javax.swing.JLabel lblendereco7;
    private javax.swing.JLabel lblendereco8;
    private javax.swing.JLabel lblendereco9;
    private javax.swing.JLabel lblnome;
    private javax.swing.JLabel lblnumero1;
    private javax.swing.JLabel lblnumero2;
    private javax.swing.JLabel lblopcional1;
    private javax.swing.JLabel lblopcional2;
    private javax.swing.JLabel lbltelefone;
    private javax.swing.JLabel lbltelefone2;
    private javax.swing.JTextField txtbairro1;
    private javax.swing.JTextField txtbairro2;
    private javax.swing.JTextField txtcomplemento1;
    private javax.swing.JTextField txtddd1;
    private javax.swing.JTextField txtddd2;
    private javax.swing.JTextField txtendereco1;
    private javax.swing.JTextField txtendereco2;
    private javax.swing.JTextField txtendereco8;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnumero1;
    private javax.swing.JTextField txtnumero2;
    private javax.swing.JTextField txttelefone1;
    private javax.swing.JTextField txttelefone2;
    // End of variables declaration//GEN-END:variables
}
